### ISSUE TITLE
"Problem with server" with snakemake

### ISSUE THREAD

**Issue by kopardev** [panoptes-organization/panoptes#149]
```
 % snakemake --snakefile Snakefile --cores 1 --wms-monitor http://127.0.0.1:42555
Problem with server: http://127.0.0.1:42555
```
Panoptes server is running on port 42555. Any idea what this error means?

**Comment by fgypas** [comment]
Hi @kopardev. How did you install `panoptes` and what OS do you use?

**Comment by kopardev** [comment]
Hello @fgypas , 
I used Option 3 from your README to install panoptes. Here are the details of my operating system:
```
% lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.9 (Maipo)
Release:	7.9
Codename:	Maipo
```
A little more context for you..... I am trying to run this on a HPC cluster. I am able to:
 * log into an interactive node on the cluster with ssh tunnel forwarding
 * fire up the panoptes server on the interactive node
 * connect my laptop to the ssh tunnel with the appropriate port number
 * I can see the panoptes webpage in my local browser with 0 workflows running

Next, when I try to run snakemake on the interactive node (again with the same port number), I get the above error.
On a separate note, is panoptes build to work on HPC clusters? Is it possible to automate port forwarding? Does it interface with slurm?

**Comment by fgypas** [comment]
So, could it be that panoptes on the interactive node is running on port `5000` and that the `42555` port is due to port forwading?

Regarding your second question, if the snakemake instance is triggered from the interactive node and panoptes is running on the same node it should work on a slurm cluster. I am not sure it will work in cases when the snakemake script is submitted as a `root` job on the slurm cluster. In the latter case panoptes and snakemake would end up in different nodes.  Does that answer your question?

**Comment by fgypas** [comment]
@kopardev I am closing the ticket due to inactivity. Feel free to re-open if needed.
